MODULE_NAME = $(notdir $(realpath ../))
CONDITION = tt_25c

all:
	python3 ../../../script/power/run.py -c $(CONDITION) -t $(MODULE_NAME) -T /top/u_$(MODULE_NAME) -n ../syn/$(MODULE_NAME).v -f ../sim/novas.fsdb