
setup_% : %
	mkdir -p $</docs $</rtl $</sim $</syn $</pwr
	cp -rf ./makefiles/Makefile.sim $</sim/Makefile
	cp -rf ./makefiles/Makefile.syn $</syn/Makefile
	cp -rf ./makefiles/Makefile.pwr $</pwr/Makefile